import type { EvidenceSourceId } from "./evidence-strength-data";

export const automationWorkflow = [
  { title: "01 · 固定输入与版本", automatic: "坐标标准化、HGVS/转录本注释、数据库版本归档和质量指标汇总。", human: "确认样本、GRCh38/37、转录本与疾病范围；查看难比对、低覆盖、低VAF等异常。", stop: "命名/参考版本不一致，质量或可检出范围不清。", artifact: "输入清单、软件与数据库版本、异常说明。" },
  { title: "02 · 选择适用规范", automatic: "检索基因–疾病关系和可用VCEP文件，列出候选规则。", human: "确认遗传模式、致病机制和规范适用范围。基因相同不等于疾病或机制相同。", stop: "工具只有通用规则，却把结果标成已按疾病特异规范解读。", artifact: "规范名称、版本、适用性理由；本地差异单列。" },
  { title: "03 · 审核候选证据", automatic: "汇集AF、计算预测、已有分类、文献候选及规则命中理由。", human: "逐条核对底层原文、数据库冲突、实验校准、表型与家系独立性。AI生成的引用必须真正打开核查。", stop: "只给分类标签，无底层来源；无法确认患者是否重复。", artifact: "原始数据→前提→代码/强度的逐条映射。" },
  { title: "04 · 复核升降级与依赖", automatic: "在明确输入和版本下算分、应用上限、标记潜在重复证据。", human: "确认相位、另一等位基因独立分类、PVS1路径及证据依赖；不能通过勾选消除真正冲突。", stop: "把病例分直接加到贝叶斯总分，或PVS1/PS3/PP3对同一机制重复加权。", artifact: "人工接受/修改/暂缓/不适用、修改前后强度及理由。" },
  { title: "05 · 病例解释与报告", automatic: "按已确认结果生成可编辑草稿、检查必填字段和术语一致性。", human: "判断变异分类是否解释该病例，处理单条AR等位基因、双重诊断、阴性局限及结果分层。", stop: "VUS用于确诊；阴性等同排除；自动文案与实际证据不一致。", artifact: "病例结论与变异分类分开，写清剩余不确定性及建议。" },
  { title: "06 · 签发与再分析", automatic: "保留审计轨迹、提示数据库/规范版本变化和待复查条目。", human: "按实验室受控SOP完成复核、签发与再联系决策，变更后重新评价受影响证据。", stop: "未经验证的软件更新直接改变历史报告；无复核人或追踪记录。", artifact: "审核人、日期、规范快照、变更理由、再分析触发条件。" },
];

export type AutomationExercise = { id: string; title: string; code: string; output: string; reveal: string; q: string; options: string[]; answer: number; rationale: string; record: string; sources: EvidenceSourceId[] };
// These are deliberately abstract boundary drills, not fabricated real patients/case reports.
export const automationExercises: AutomationExercise[] = [
  { id: "auto-pm3-phase", title: "两位先证者不必等于两分", code: "PM3", output: "软件统计到两位不同家系先证者，建议PM3_Strong。", reveal: "均为隐性病受累者且符合稀有度要求；相位未知，另一变异均为LP，但为两种不同变异；分类相互独立。", q: "审核后应怎样处理PM3？", options: ["保留Strong：两位就是两分", "改为Supporting：0.25+0.25=0.5", "改为VeryStrong", "LP不能用于PM3"], answer: 1, rationale: "PM3 v1.0未知相位且另一变异为LP，每例0.25分，合计0.5达Supporting。不能仅按先证者个数升级。", record: "记录每位先证者的相位、另一变异及独立分类来源。", sources: ["pm3"] },
  { id: "auto-pm3-cap", title: "纯合观察的总上限", code: "PM3", output: "软件对8个已去重纯合观察计4分，建议PM3_VeryStrong。", reveal: "这些是符合通用PM3前提的独立受累者，无其他反式观察，采用PM3 v1.0而非VCEP特别规则。", q: "正确的通用模型处理是？", options: ["每个纯合算两条等位基因", "仍为4分", "该类封顶1分，对应PM3中等", "纯合永远不计分"], answer: 2, rationale: "纯合默认每例0.5，但这一类合计最多贡献1分，不能靠增加纯合观察无限升级。", record: "保留原始4分、封顶1分及所用规范。", sources: ["pm3"] },
  { id: "auto-pvs1", title: "截短标签不是PVS1结论", code: "PVS1", output: "软件看到stop-gained，自动赋PVS1。", reveal: "注释位于末端编码区；疾病相关转录本和LoF机制尚未核实，也没有NMD/关键区域分析。", q: "下一步是什么？", options: ["暂停赋值，核查机制与PVS1决策树", "仅因末端就判良性", "固定降为Supporting即可", "保留PVS1并加PM4"], answer: 0, rationale: "适用性缺失不能靠随意降一级解决。先核实LoF机制、转录本、NMD和蛋白影响，才可能选择合适分支。", record: "保留原始自动命中；将状态改为待补证而非已确认。", sources: ["pvs1"] },
  { id: "auto-denovo", title: "父母阴性与亲缘确认", code: "PS2 / PM6", output: "父母变异检测阴性，工具自动给PS2_Strong。", reveal: "双方检测质量合格，但未经亲缘验证；表型与基因高度特异，只有一位先证者，无特殊遗传模式限制。", q: "按de novo v1.1如何处理？", options: ["给PS2和PM6两条", "父母未确认亲缘完全不能用证据", "保留PS2_Strong", "使用未确认亲缘列1分，对应PM6中等"], answer: 3, rationale: "检测阴性和亲缘确认不同。此题双方已检测变异，可用未确认亲缘列；高度特异的一例计1分。", record: "分别记录父母变异检测与亲缘验证状态。", sources: ["denovo"] },
  { id: "auto-pm2", title: "数据库未见不等于强证据", code: "PM2", output: "gnomAD未检出，软件赋PM2中等，并称非常罕见可升强。", reveal: "尚未检查位点覆盖、祖源和质量；未提供疾病特异阈值。", q: "先做哪项决定？", options: ["因为零频率直接升强", "暂缓；补齐覆盖和阈值，符合通用建议时为Supporting", "未见就是良性", "只增加预测软件即可"], answer: 1, rationale: "PM2通用建议为Supporting；首先确认未检出是否有解释力，缺失覆盖不能当作已证实的人群缺失。", record: "数据库版本、AC/AN、质量、覆盖、阈值。", sources: ["pm2"] },
  { id: "auto-functional", title: "显著性不等于功能证据强度", code: "PS3 / BS3", output: "实验p<0.001，工具赋PS3_Strong。", reveal: "实验无已知致病/良性变异校准，疾病机制匹配与检测判别性能未交代。", q: "如何审核？", options: ["p值小于0.05就自动Strong", "多个p值可以累加", "核查实验相关性与验证质量，不从p值推强度", "没有校准应直接给BS3"], answer: 2, rationale: "p值与OddsPath不是同一概念。功能证据需证明实验的疾病相关性及判别性能，不能仅凭显著差异赋强证据。", record: "实验系统、对照、验证、读数与未满足条件。", sources: ["functional"] },
  { id: "auto-splicing", title: "同一剪接效应被算了三次", code: "PVS1 / PS3 / PP3", output: "预测剪接异常、RNA证实同一异常，软件同时给PVS1、PS3和PP3。", reveal: "PS3条目只是这次RNA剪接实验，没有额外独立的蛋白功能实验。", q: "应该怎样处理？", options: ["按剪接框架评价PVS1(RNA)，去除同一效应重复加权", "三种来源所以必然独立", "删掉全部RNA证据", "只要工具支持就保留全部"], answer: 0, rationale: "同一剪接后果不是三条独立证据。RNA结果按剪接框架并结合PVS1决策树确定强度，不能照搬一般PS3条目重复计入。", record: "建立证据依赖关系并说明保留和移除理由。", sources: ["splicing"] },
  { id: "auto-clinvar", title: "数据库分类不是底层证据", code: "PP5 / BP6", output: "工具找到ClinVar致病标签，附加PP5。", reveal: "同一提交的原始证据已被计入其他代码，且尚未核对提交对应的疾病和时间。", q: "正确处理是？", options: ["星级越多PP5越强", "换成PS1就可以", "自动覆盖本地分类", "不使用PP5，追溯并去重底层证据"], answer: 3, rationale: "ClinGen建议不再使用PP5/BP6。要查看提交疾病、日期、冲突和底层依据，不将分类标签再次当独立证据。", record: "提交级审查结论与原始证据映射。", sources: ["hub"] },
  { id: "auto-prediction", title: "多工具投票不能升级", code: "PP3 / BP4", output: "四个预测工具一致有害，自动给PP3_Strong。", reveal: "工具存在训练数据重叠，未预先选定模型，也未提供阈值校准；无功能实验。", q: "该如何改？", options: ["预选并核查适用校准工具，不能按票数定强度", "四票等于四条Supporting", "再多跑工具直到凑够Strong", "预测一致即为PS3"], answer: 0, rationale: "预测工具往往相关。升级需要工具特异的校准依据，而不是票数；预测与实验必须分开。", record: "模型版本、原始分、阈值出处、变异类型与依赖。", sources: ["computational"] },
  { id: "auto-case", title: "变异分级不等于病例确诊", code: "病例级解释", output: "一个隐性病基因检出一条P变异，报告草稿写“已分子确诊”。", reveal: "只确认一个杂合等位基因；另一条变异未找到，检测能力和升级路径尚未说明。", q: "如何复核这段草稿？", options: ["P变异就能确诊所有遗传模式", "保留确诊但加免责声明", "分开记录变异分类与病例未解决状态，核查第二等位基因和检测局限", "将该P降为VUS以匹配病例"], answer: 2, rationale: "变异致病性与病例解释是不同层次。不能把缺少第二等位基因的问题通过修改已成立的变异分类来解决，也不能直接写已分子确诊。", record: "已确认发现、未解决假设、检测局限和后续评估建议。", sources: ["acmg"] },
];
